version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9093:9093" # Client esterni
      - "9094:9094" # AKHQ interno
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=no
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9093,INTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9093,INTERNAL://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:SASL_SSL,INTERNAL:SSL
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL

      # SSL config esistente (non toccare)
      - KAFKA_CFG_SSL_CLIENT_AUTH=required
      - KAFKA_CERTIFICATE_PASSWORD=password123
      - KAFKA_TLS_TYPE=JKS
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=password123
      - KAFKA_CFG_SSL_KEY_PASSWORD=password123
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=password123
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=

      # SASL SCRAM config
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=SCRAM-SHA-256,SCRAM-SHA-512
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SCRAM-SHA-256

    volumes:
      - ./certs:/opt/bitnami/kafka/config/certs

  akhq:
    image: tchiotludo/akhq:0.24.0
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-internal:
              properties:
                bootstrap.servers: "kafka:9094"
                security.protocol: SSL
                ssl.truststore.location: /certs/kafka.truststore.jks
                ssl.truststore.password: password123
                ssl.keystore.location: /certs/client.keystore.jks
                ssl.keystore.password: password123
                ssl.key.password: password123
                ssl.endpoint.identification.algorithm: ""
    volumes:
      - ./certs:/certs
