POST http://localhost:1337/api/pubs
Authorization: Bearer YOUR_API_TOKEN
Content-Type: application/json

{
  "data": {
    "name": "Nuovo18",
    "address": "Via del Vaticano",
    "avgPrice": 19
  }
}